node_env: production
env: devl
account: 541843007032
region: us-east-1

ApplicationName: JohnDeereDataCatalog2

EC2InstanceType: m5.2xlarge
EC2MinNumberOfInstances: 2
EC2MaxNumberOfInstances: 3

VpcId: vpc-882698ef
PrivateSubnets: subnet-2762390d,subnet-4883a610
PublicSubnets: subnet-4c83a614,subnet-2462390e
DeereNetworkSSH: sg-1671396d
SslArn: arn:aws:acm:us-east-1:541843007032:certificate/5dd5c254-2056-44e5-9e43-f4c61b80ec70
CName: dataGovernanceCenter2

URLPrefix: data-catalog2
URLSuffix: vpn-devl.us.e03.c01.johndeerecloud.com
BaseURL: data-catalog-dev.deere.com
HostedZoneId: Z2OQCZSODIVDU5

collibraUserName: govUI_devl

deereTaggingComponent: enterprise-data-governance-center
newRelicAppName: JD Data Catalog Devl

APPDYNAMICSCONTROLLERHOSTNAME: deere-nonprod.saas.appdynamics.com
APPDYNAMICSCONTROLLERPORT: 443
APPDYNAMICSAGENTACCOUNTNAME: deere-nonprod
APPDYNAMICSAGENTACCOUNTACCESSKEY: 860604d3-e46d-4c53-b884-2accc52a8297
APPDYNAMICSAGENTAPPLICATIONNAME: EDLDataCatalogDev
APPDYNAMICSAGENTNODENAME: EDLDataCatalog
APPDYNAMICSAGENTTIERNAME: data-catalog-dev.edl.deere.com
